name: 'THAT Public JavaScript Action'
description: 'THIS one actually does something and prints basic info about a GitHub user.'

inputs:
  name:
    description: 'GitHub username'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.name }}